### ISSUE TITLE
problems to build on macOS Catalina

### ISSUE THREAD

**Issue by montoyamoraga** [pblasser/shbobo#1]
hi!

i tried to build shlisp on a macOS Catalina, and from what i understood on the makefile, the flag -m32 builds it on 32 bit architecture, so i removed it and i was able to build it.

i don't know if this is the right way to fix it, happy to help :)

**Comment by pblasser** [comment]
cool.
thanks, i am new to github.
the -m32 was for my good friend who has an ancient computer.
well he's still my good friend but i think he has a new computer
i see catalina is the newest, apart from big sur... good good, thanks again!
> hi!
>
> i tried to build shlisp on a macOS Catalina, and from what i understood on
> the makefile, the flag -m32 builds it on 32 bit architecture, so i removed
> it and i was able to build it.
>
> i don't know if this is the right way to fix it, happy to help :)
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pblasser/shbobo/issues/1


-- 
www.ciat-lonbarde.net

**Comment by pblasser** [comment]
hey, do you have any preferences as to what the lisp functions should be
named?
i was thinking "def" is define a var as such and such
def could also replace "set"
"fun" is lambda like how functions are made <fun [a b c] <+ a b c>>
"car" and "cdr" would be the same
theres a function for each "fish" "soup" "tank" and "boat"
which return () {} [] <> respectively with whatever you want to put in them
and then squiggly math primitives make it fun:
~!@#$%^&*-+=:?/


> hi!
>
> i tried to build shlisp on a macOS Catalina, and from what i understood on
> the makefile, the flag -m32 builds it on 32 bit architecture, so i removed
> it and i was able to build it.
>
> i don't know if this is the right way to fix it, happy to help :)
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pblasser/shbobo/issues/1


-- 
www.ciat-lonbarde.net

**Comment by montoyamoraga** [comment]
hi @pblasser i'm not familiar with lisp,
i shared this repo on the lines forum
https://llllllll.co/t/shbobo-shnth-patches-and-appreciation/7385
i'm happy to ask for help with documentation there
now that this repo is published i will continue my documentation and studies
https://github.com/montoyamoraga/shbobo-studies
:)

**Comment by montoyamoraga** [comment]
this was fixed and addressed already
