### ISSUE TITLE
compiling shlisp under debian 10

### ISSUE THREAD

**Issue by michal-cab** [pblasser/shbobo#10]
compiling shlisp under debian 10 went like:

gcc minilisp.cpp -xc++ -DLINUSTORWALDS -lusb-1.0 -oshlisp
minilisp.cpp: In function ‘Obj* apply(Obj*, Obj*, Obj*)’:
minilisp.cpp:484:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
minilisp.cpp: In function ‘Obj* eval(Obj*, Obj*)’:
minilisp.cpp:531:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/usr/bin/ld: /tmp/ccp3f0nv.o: in function `prim_euro(Obj*, Obj*)':
minilisp.cpp:(.text+0x2536): undefined reference to `pow'
/usr/bin/ld: /tmp/ccp3f0nv.o: in function `main':
minilisp.cpp:(.text+0x520a): undefined reference to `chubONE()'
collect2: error: ld returned 1 exit status
make: *** [makefile:34: main] Error 1

first error can be repaired by adding -lm into lagsLinux in makefile.
but dont know how to solve second error :/

**Comment by pblasser** [comment]
Hi MC, thanks for your feedback. I added the -lm. i added the chubONE().
should compile now!
my advice for linuxheads is to start with this: just compile shlisp. then try to get jish.jar running (java -jar jish.jar)
