### ISSUE TITLE
Primitives

### ISSUE THREAD

**Issue by Thomasbru** [pblasser/shbobo#13]
I guess this is still experimental, but playing around a bit with <>. Is there a car error?
I keep getting "Don't know how to handle \\" thrown, and I also see that car is defined with an extra " in minilisp.c. As "\\"", I mean.
Issue persists trying @\ as well.

Totally unrelated: I have spent some time trying out the melody op, and have gotten some nice results using it as a (very lofi) sampler with wind as input. However, when adding multiple melodies, the sample rate seems to slow down. Is this due to the memory management of a melody, or any tips on how to approach this? Besides embracing it, I mean?

Thanks for keeping up development, one of my favourite instruments!

**Comment by Thomasbru** [comment]
Edit: forgot to escape \\ in my original post, making my comment look odd.

**Comment by pblasser** [comment]
Hi, thans for the email.

    add_primitive(env, "\"", prim_car);
so that means car is actually like as follows:
<" mylist>
it is simply a single quote mark
hope that helps.
yes, melody will slow down sample rate if you add more.
definitely experimental there, thanks for probing those depths.
cheers, peter



> I guess this is still experimental, but playing around a bit with <>. Is
> there a car error?
> I keep getting "Don't know how to handle \\" thrown, and I also see that
> car is defined with an extra " in minilisp.c. As "\\"", I mean.
> Issue persists trying @\ as well.
>
> Totally unrelated: I have spent some time trying out the melody op, and
> have gotten some nice results using it as a (very lofi) sampler with wind
> as input. However, when adding multiple melodies, the sample rate seems to
> slow down. Is this due to the memory management of a melody, or any tips
> on how to approach this? Besides embracing it, I mean?
>
> Thanks for keeping up development, one of my favourite instruments!
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/pblasser/shbobo/issues/13
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***>


-- 
www.ciat-lonbarde.net

**Comment by Thomasbru** [comment]
Aha! Misreading on my end then. Thanks for replying!

Best,
Thomas
