### ISSUE TITLE
change name of opcode slave

### ISSUE THREAD

**Issue by montoyamoraga** [pblasser/shbobo#7]
more info here
https://cdm.link/2020/06/lets-dump-master-slave-terms/ 
:)

**Comment by pblasser** [comment]
i promise i will, just gotta switch to linux to do the regex properly

> more info here
> https://cdm.link/2020/06/lets-dump-master-slave-terms/
> :)
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pblasser/shbobo/issues/7


-- 
www.ciat-lonbarde.net

**Comment by pblasser** [comment]
done on macintosh

**Comment by pblasser** [comment]
done
