### ISSUE TITLE
MAC BIG SUR USB PIPES

### ISSUE THREAD

**Issue by pblasser** [pblasser/shbobo#9]
you may not want to switch to big sur until this usb io library thingie is fixed.
i spent a day tinkering with it
IOHIDDeviceSetReport is supposed to send your fish data to the shnth
it should return kIOReturnSuccess
instead it immediately returns 0005000 which is kUSBHostReturnPipeStalled
that means the host has stalled it, not the device btw.
there:s something about clearing pipes as a deephack for it, but imho it should work as advertised on the box. 
this might have something to do with security, but its hard to figure out. can someone interrogate this transaction?

https://github.com/pblasser/shbobo/blob/051791915e4d42154323cfd6ec55a725ed1ed517/sorce/shlisp/chub_mac.h#L71

**Comment by Thomasbru** [comment]
Is this still an issue? Is fish and Shnth talking on Big Sur?

**Comment by eclectics** [comment]
I don't think so. I just tried to do something with the synth having updated a few weeks ago, and I can't load any new patches.

**Comment by biomassa** [comment]
can confirm it's still a no go :(

**Comment by pblasser** [comment]
Thanks for your patience. Happy to say I just fixed it. Now Im gonna go shopping for  chocolates and spirits at LIDL.

**Comment by Thomasbru** [comment]
Thanks for your efforts. Happy LIDL shopping and holidays.

**Comment by cfdrake** [comment]
+1 Enjoy the chocolates! Thanks for fixing this, seemed like a rough one!

**Comment by biomassa** [comment]
many thanks for fixing it PB!
